In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("weather_data.csv")
data.head()

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,precip_mm,temp_c,wind_kmph
0,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 00:00:00,79,0.0,26.6,9.7
1,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 01:00:00,79,0.0,26.6,9.7
2,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 02:00:00,79,0.0,26.6,9.7
3,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 03:00:00,79,0.0,26.6,9.7
4,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 04:00:00,79,0.0,26.6,9.7

In [3]:
data.tail()

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,precip_mm,temp_c,wind_kmph
49681,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 20:00:00,79,0.0,28.7,14.0
49682,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 21:00:00,79,0.0,28.7,14.0
49683,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 22:00:00,79,0.0,28.7,14.0
49684,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 23:00:00,79,0.0,28.7,14.0
49685,1011.0,22,24.3,7.0,10.0,13.7,Ota,Clear,2023-05-12 00:00:00,78,0.0,28.6,13.7

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49686 entries, 0 to 49685
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Atmospheric Pressure  49686 non-null  float64
 1   Cloud Cover (%)       49686 non-null  int64
 2   Dew Point             49686 non-null  float64
 3   UV Index              49686 non-null  float64
 4   Visibility            49686 non-null  float64
 5   Wind Gust             49686 non-null  float64
 6   city                  49686 non-null  object
 7   condition             49686 non-null  object
 8   date                  49686 non-null  object
 9   humidity              49686 non-null  int64
 10  precip_mm             49686 non-null  float64
 11  temp_c                49686 non-null  float64
 12  wind_kmph             49686 non-null  float64
dtypes: float64(8), int64(2), object(3)
memory usage: 4.9+ MB

In [5]:
data.describe()

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,humidity,precip_mm,temp_c,wind_kmph
count,49686.000000,49686.000000,49686.000000,49686.000000,49686.000000,49686.000000,49686.000000,49686.000000,49686.000000,49686.000000
mean,1011.750151,42.859176,18.252721,7.197178,9.249185,9.838337,72.541138,0.099033,24.736107,9.838337
std,2.191939,34.265228,7.664778,1.208997,2.290135,4.499555,24.436116,0.402762,2.459998,4.499555
min,1002.000000,0.000000,-11.800000,5.000000,0.000000,0.000000,6.000000,0.000000,16.900000,0.000000
25%,1010.000000,8.000000,19.600000,6.000000,10.000000,6.100000,72.000000,0.000000,22.900000,6.100000
50%,1012.000000,40.000000,21.100000,7.000000,10.000000,9.700000,80.000000,0.000000,24.600000,9.700000
75%,1013.000000,75.000000,22.400000,8.000000,10.000000,13.700000,89.000000,0.000000,26.600000,13.700000
max,1018.000000,100.000000,24.800000,10.000000,10.000000,27.400000,99.000000,4.300000,33.500000,27.400000

In [6]:
#Checking the number of Cities in the dataset
data["city"].value_counts()

Lagos            8281
Port Harcourt    8281
Kano             8281
Abuja            8281
Ibadan           8281
Ota              8281
Name: city, dtype: int64

In [7]:
#Checking tthe Conditions available in the dataset
data["condition"].value_counts()

Clear                             20812
Partly cloudy                      8232
Cloudy                             7488
Patchy rain possible               5737
Overcast                           4032
Moderate rain at times              816
Moderate or heavy rain shower       744
Thundery outbreaks possible         696
Heavy rain at times                 360
Light rain shower                   360
Patchy light rain with thunder      264
Mist                                145
Name: condition, dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

In [10]:
# Initialize LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the "city" column
data['city_encoded'] = label_encoder.fit_transform(data['city'])

# Fit and transform the "condition" column
data['condition_encoded'] = label_encoder.fit_transform(data['condition'])

# Print the updated dataset
print(data.head(10))

   Atmospheric Pressure  Cloud Cover (%)  Dew Point  UV Index  Visibility  \
0                1012.0               85       22.7       7.0        10.0
1                1012.0               85       22.7       7.0        10.0
2                1012.0               85       22.7       7.0        10.0
3                1012.0               85       22.7       7.0        10.0
4                1012.0               85       22.7       7.0        10.0
5                1012.0               85       22.7       7.0        10.0
6                1012.0               85       22.7       7.0        10.0
7                1012.0               85       22.7       7.0        10.0
8                1012.0               85       22.7       7.0        10.0
9                1012.0               85       22.7       7.0        10.0

   Wind Gust   city condition                 date  humidity  precip_mm  \
0        9.7  Lagos  Overcast  2022-06-01 00:00:00        79        0.0
1        9.7  Lagos  Overcast  2022-06-01 01:00:00        79        0.0
2        9.7  Lagos  Overcast  2022-06-01 02:00:00        79        0.0
3        9.7  Lagos  Overcast  2022-06-01 03:00:00        79        0.0
4        9.7  Lagos  Overcast  2022-06-01 04:00:00        79        0.0
5        9.7  Lagos  Overcast  2022-06-01 05:00:00        79        0.0
6        9.7  Lagos  Overcast  2022-06-01 06:00:00        79        0.0
7        9.7  Lagos  Overcast  2022-06-01 07:00:00        79        0.0
8        9.7  Lagos  Overcast  2022-06-01 08:00:00        79        0.0
9        9.7  Lagos  Overcast  2022-06-01 09:00:00        79        0.0

   temp_c  wind_kmph  city_encoded  condition_encoded
0    26.6        9.7             3                  7
1    26.6        9.7             3                  7
2    26.6        9.7             3                  7
3    26.6        9.7             3                  7
4    26.6        9.7             3                  7
5    26.6        9.7             3                  7
6    26.6        9.7             3                  7
7    26.6        9.7             3                  7
8    26.6        9.7             3                  7
9    26.6        9.7             3                  7

In [11]:
data.head(10)

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,precip_mm,temp_c,wind_kmph,city_encoded,condition_encoded
0,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 00:00:00,79,0.0,26.6,9.7,3,7
1,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 01:00:00,79,0.0,26.6,9.7,3,7
2,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 02:00:00,79,0.0,26.6,9.7,3,7
3,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 03:00:00,79,0.0,26.6,9.7,3,7
4,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 04:00:00,79,0.0,26.6,9.7,3,7
5,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 05:00:00,79,0.0,26.6,9.7,3,7
6,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 06:00:00,79,0.0,26.6,9.7,3,7
7,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 07:00:00,79,0.0,26.6,9.7,3,7
8,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 08:00:00,79,0.0,26.6,9.7,3,7
9,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 09:00:00,79,0.0,26.6,9.7,3,7

In [12]:
data.tail(10)

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,precip_mm,temp_c,wind_kmph,city_encoded,condition_encoded
49676,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 15:00:00,79,0.0,28.7,14.0,4,8
49677,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 16:00:00,79,0.0,28.7,14.0,4,8
49678,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 17:00:00,79,0.0,28.7,14.0,4,8
49679,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 18:00:00,79,0.0,28.7,14.0,4,8
49680,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 19:00:00,79,0.0,28.7,14.0,4,8
49681,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 20:00:00,79,0.0,28.7,14.0,4,8
49682,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 21:00:00,79,0.0,28.7,14.0,4,8
49683,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 22:00:00,79,0.0,28.7,14.0,4,8
49684,1011.0,28,24.8,7.0,10.0,14.0,Ota,Partly cloudy,2023-05-11 23:00:00,79,0.0,28.7,14.0,4,8
49685,1011.0,22,24.3,7.0,10.0,13.7,Ota,Clear,2023-05-12 00:00:00,78,0.0,28.6,13.7,4,0

In [18]:
data[data['city']=="Abuja"]

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,precip_mm,temp_c,wind_kmph,city_encoded,condition_encoded
24843,1012.0,10,20.7,8.0,10.0,3.2,Abuja,Clear,2022-06-01 00:00:00,75,0.0,25.3,3.2,0,0
24844,1012.0,10,20.7,8.0,10.0,3.2,Abuja,Clear,2022-06-01 01:00:00,75,0.0,25.3,3.2,0,0
24845,1012.0,10,20.7,8.0,10.0,3.2,Abuja,Clear,2022-06-01 02:00:00,75,0.0,25.3,3.2,0,0
24846,1012.0,10,20.7,8.0,10.0,3.2,Abuja,Clear,2022-06-01 03:00:00,75,0.0,25.3,3.2,0,0
24847,1012.0,10,20.7,8.0,10.0,3.2,Abuja,Clear,2022-06-01 04:00:00,75,0.0,25.3,3.2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33119,1010.0,79,21.1,8.0,10.0,7.6,Abuja,Patchy rain possible,2023-05-11 20:00:00,72,0.1,26.7,7.6,0,10
33120,1010.0,79,21.1,8.0,10.0,7.6,Abuja,Patchy rain possible,2023-05-11 21:00:00,72,0.1,26.7,7.6,0,10
33121,1010.0,79,21.1,8.0,10.0,7.6,Abuja,Patchy rain possible,2023-05-11 22:00:00,72,0.1,26.7,7.6,0,10
33122,1010.0,79,21.1,8.0,10.0,7.6,Abuja,Patchy rain possible,2023-05-11 23:00:00,72,0.1,26.7,7.6,0,10
33123,1012.0,77,22.0,8.0,9.0,10.4,Abuja,Patchy rain possible,2023-05-12 00:00:00,80,0.7,25.6,10.4,0,10

In [21]:
data['condition'].value_counts()

Clear                             20812
Partly cloudy                      8232
Cloudy                             7488
Patchy rain possible               5737
Overcast                           4032
Moderate rain at times              816
Moderate or heavy rain shower       744
Thundery outbreaks possible         696
Heavy rain at times                 360
Light rain shower                   360
Patchy light rain with thunder      264
Mist                                145
Name: condition, dtype: int64

In [33]:
data[data['condition']=="Patchy light rain with thunder"]

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,precip_mm,temp_c,wind_kmph,city_encoded,condition_encoded
6768,1010.0,82,24.0,7.0,10.0,10.4,Lagos,Patchy light rain with thunder,2023-03-10 00:00:00,77,0.2,28.4,10.4,3,9
6769,1010.0,82,24.0,7.0,10.0,10.4,Lagos,Patchy light rain with thunder,2023-03-10 01:00:00,77,0.2,28.4,10.4,3,9
6770,1010.0,82,24.0,7.0,10.0,10.4,Lagos,Patchy light rain with thunder,2023-03-10 02:00:00,77,0.2,28.4,10.4,3,9
6771,1010.0,82,24.0,7.0,10.0,10.4,Lagos,Patchy light rain with thunder,2023-03-10 03:00:00,77,0.2,28.4,10.4,3,9
6772,1010.0,82,24.0,7.0,10.0,10.4,Lagos,Patchy light rain with thunder,2023-03-10 04:00:00,77,0.2,28.4,10.4,3,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49320,1010.0,87,24.3,6.0,10.0,11.9,Ota,Patchy light rain with thunder,2023-04-26 19:00:00,79,0.2,28.4,11.9,4,9
49321,1010.0,87,24.3,6.0,10.0,11.9,Ota,Patchy light rain with thunder,2023-04-26 20:00:00,79,0.2,28.4,11.9,4,9
49322,1010.0,87,24.3,6.0,10.0,11.9,Ota,Patchy light rain with thunder,2023-04-26 21:00:00,79,0.2,28.4,11.9,4,9
49323,1010.0,87,24.3,6.0,10.0,11.9,Ota,Patchy light rain with thunder,2023-04-26 22:00:00,79,0.2,28.4,11.9,4,9
49324,1010.0,87,24.3,6.0,10.0,11.9,Ota,Patchy light rain with thunder,2023-04-26 23:00:00,79,0.2,28.4,11.9,4,9

In [34]:
# Convert date column to datetime type
data['date'] = pd.to_datetime(data['date'])

# Extract useful features
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month
data['day'] = data['date'].dt.day
data['hour'] = data['date'].dt.hour

# Perform cyclical encoding on month and hour features
data['month_sin'] = np.sin(2 * np.pi * data['month'] / 12)
data['month_cos'] = np.cos(2 * np.pi * data['month'] / 12)
data['hour_sin'] = np.sin(2 * np.pi * data['hour'] / 24)
data['hour_cos'] = np.cos(2 * np.pi * data['hour'] / 24)


data.head(10)

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,...,city_encoded,condition_encoded,year,month,day,hour,month_sin,month_cos,hour_sin,hour_cos
0,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 00:00:00,79,...,3,7,2022,6,1,0,1.224647e-16,-1.0,0.000000,1.000000e+00
1,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 01:00:00,79,...,3,7,2022,6,1,1,1.224647e-16,-1.0,0.258819,9.659258e-01
2,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 02:00:00,79,...,3,7,2022,6,1,2,1.224647e-16,-1.0,0.500000,8.660254e-01
3,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 03:00:00,79,...,3,7,2022,6,1,3,1.224647e-16,-1.0,0.707107,7.071068e-01
4,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 04:00:00,79,...,3,7,2022,6,1,4,1.224647e-16,-1.0,0.866025,5.000000e-01
5,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 05:00:00,79,...,3,7,2022,6,1,5,1.224647e-16,-1.0,0.965926,2.588190e-01
6,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 06:00:00,79,...,3,7,2022,6,1,6,1.224647e-16,-1.0,1.000000,6.123234e-17
7,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 07:00:00,79,...,3,7,2022,6,1,7,1.224647e-16,-1.0,0.965926,-2.588190e-01
8,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 08:00:00,79,...,3,7,2022,6,1,8,1.224647e-16,-1.0,0.866025,-5.000000e-01
9,1012.0,85,22.7,7.0,10.0,9.7,Lagos,Overcast,2022-06-01 09:00:00,79,...,3,7,2022,6,1,9,1.224647e-16,-1.0,0.707107,-7.071068e-01

In [35]:
#Normalizing the Data using Standization
from sklearn.preprocessing import StandardScaler

In [36]:
#Features to be standardized
features_to_scale = ["Atmospheric Pressure", "Cloud Cover (%)", "Dew Point", "UV Index",
                     "Visibility", "Wind Gust", "humidity", "precip_mm", "temp_c", "wind_kmph"]

#StandardScaler object
scaler = StandardScaler()

# Fit the scaler on the selected features
scaler.fit(data[features_to_scale])

# Transform the selected features using the scaler
data[features_to_scale] = scaler.transform(data[features_to_scale])

data.head(10)

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,city,condition,date,humidity,...,city_encoded,condition_encoded,year,month,day,hour,month_sin,month_cos,hour_sin,hour_cos
0,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 00:00:00,0.264319,...,3,7,2022,6,1,0,1.224647e-16,-1.0,0.000000,1.000000e+00
1,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 01:00:00,0.264319,...,3,7,2022,6,1,1,1.224647e-16,-1.0,0.258819,9.659258e-01
2,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 02:00:00,0.264319,...,3,7,2022,6,1,2,1.224647e-16,-1.0,0.500000,8.660254e-01
3,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 03:00:00,0.264319,...,3,7,2022,6,1,3,1.224647e-16,-1.0,0.707107,7.071068e-01
4,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 04:00:00,0.264319,...,3,7,2022,6,1,4,1.224647e-16,-1.0,0.866025,5.000000e-01
5,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 05:00:00,0.264319,...,3,7,2022,6,1,5,1.224647e-16,-1.0,0.965926,2.588190e-01
6,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 06:00:00,0.264319,...,3,7,2022,6,1,6,1.224647e-16,-1.0,1.000000,6.123234e-17
7,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 07:00:00,0.264319,...,3,7,2022,6,1,7,1.224647e-16,-1.0,0.965926,-2.588190e-01
8,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 08:00:00,0.264319,...,3,7,2022,6,1,8,1.224647e-16,-1.0,0.866025,-5.000000e-01
9,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,Lagos,Overcast,2022-06-01 09:00:00,0.264319,...,3,7,2022,6,1,9,1.224647e-16,-1.0,0.707107,-7.071068e-01

In [39]:
#Create the training dataset

training_data = data.drop(['city', 'condition', 'date'], axis=1)
training_data.head(10)

,Atmospheric Pressure,Cloud Cover (%),Dew Point,UV Index,Visibility,Wind Gust,humidity,precip_mm,temp_c,wind_kmph,city_encoded,condition_encoded,year,month,day,hour,month_sin,month_cos,hour_sin,hour_cos
0,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,0,1.224647e-16,-1.0,0.000000,1.000000e+00
1,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,1,1.224647e-16,-1.0,0.258819,9.659258e-01
2,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,2,1.224647e-16,-1.0,0.500000,8.660254e-01
3,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,3,1.224647e-16,-1.0,0.707107,7.071068e-01
4,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,4,1.224647e-16,-1.0,0.866025,5.000000e-01
5,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,5,1.224647e-16,-1.0,0.965926,2.588190e-01
6,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,6,1.224647e-16,-1.0,1.000000,6.123234e-17
7,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,7,1.224647e-16,-1.0,0.965926,-2.588190e-01
8,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,8,1.224647e-16,-1.0,0.866025,-5.000000e-01
9,0.113987,1.229855,0.580229,-0.163094,0.327851,-0.030745,0.264319,-0.245888,0.757689,-0.030745,3,7,2022,6,1,9,1.224647e-16,-1.0,0.707107,-7.071068e-01

In [41]:
#Saving the new datafram to a CSV file
training_data.to_csv('Training_data.csv', index=False)